ariga/atlas-action

src/main.ts
=> src/main: avoid double output printout

__tests__/cloud.test.ts, __tests__/reporting.test.ts, __tests__/testdata/runs/cloudreports.expected.txt, __tests__/testdata/runs/cloudreports.txt
tests for: https://github.com/ariga/atlas-action/commit/6ad0381b6cc074278416f89bbf5fdca18ec1c348
=> __test__: add tests for ariga cloud reports

atlasaction/comment.tmpl
I have PR that stuck on red, because of error to evaluate template
=> fix comment template

atlasaction/action.go, atlasaction/action_test.go
=> atlasaction: add check runs comment in migrate lint action

atlasaction/action.go, atlasaction/action_test.go
sending suggestion when file is not in the PR causes the action to fail, see:
https://github.com/ronenlu/test_migration/actions/runs/7986897179/job/21808230475?pr=170#step:5:77
=> atlasaction: dont send suggestion comment if file is not in the PR

atlasaction/action.go, atlasaction/action_test.go, atlasaction/gh_action.go, cmd/atlas-action/main.go, cmd/atlas-action/main_test.go
The purpose of the PR is to reduce the dependency on Atlas action so that we can integrate more easily with CircleCI by implementing the `Action` interface.
=> atlasaction: abstract github action

.github/workflows/ci-go.yaml, README.md, atlasaction/action.go, atlasaction/action_test.go, atlasaction/mock-atlas-test.sh, atlasaction/testdata/migrations.test.hcl, cmd/atlas-action/main.go, go.mod, go.sum, migrate/test/action.yaml, migrate/test/dist/index.js, migrate/test/index.js, package.json
**log `atlas migrate test` when action fail:**
**log `atlas migrate test` when action success:**
=> all: add support for migrate test

migrate/apply/dist/index.js, migrate/down/dist/index.js, migrate/lint/dist/index.js, migrate/push/dist/index.js, migrate/test/dist/index.js, schema/test/dist/index.js, shim/index.js
- **Revert "shim: fixed the path for atlas-binary (#186)"**
- **shim: fixed download logic**
=> shim: fixed download logic

migrate/apply/dist/index.js, migrate/down/dist/index.js, migrate/lint/dist/index.js, migrate/push/dist/index.js, migrate/test/dist/index.js, schema/test/dist/index.js, shim/index.js
- **shim: added comment for the flow**
- **chore: build**
=> shim: added comment for the flow

.github/workflows/cd.yaml
https://pkg.go.dev/cmd/link
- `-s`: Omit the symbol table and debug information.
- `-w`: Omit the DWARF symbol table.
=> build: strip the debugging information

atlasaction/action.go, atlasaction/action_test.go, atlasaction/circleci_action.go, atlasaction/comments/suggestion.tmpl, cmd/atlas-action/main.go
- **migrate/apply: no need GH client to report summary**
- **atlasaction: detach logic of suggestions from GH Client**
=> atlasaction: thin github client for abstraction

atlasaction/action.go, atlasaction/comments/schema-plan.tmpl, go.mod, schema/plan/action.yml
- **chore: bump go**
- **schema/plan: optional the `from` input**
- **schema/plan: push edited plan in the pending status**
=> schema/apply: fixed comments and inputs

atlasaction/comments/schema-plan.tmpl, atlasaction/testdata/gitlab/schema-plan.txtar
=> atlasaction/comments: update edit this plan comment

schema/push/action.yml
The description is for the schema, not the changes.
=> schema/push: fix description input copy

README.md, atlasaction/action.go, atlasaction/action_test.go, migrate/apply/action.yml
requested by: https://discord.com/channels/930720389120794674/1339516327831797780/1339516327831797780
=> atlasaction: add amount input to migrate apply

atlasaction/action.go, atlasaction/action_test.go, go.mod, go.sum
fix this [err](https://github.com/ariga/atlas-action/actions/runs/13808629196/job/38628969761#step:5:18):
=> Fix whoami signature 

atlasaction/action.go
This pull request includes changes to the `atlasaction/action.go` file to refactor the `MigrateDown` function and add a new helper function to handle approval waiting logic. The most important changes include simplifying the retry logic within `MigrateDown` and introducing the `waitingForApproval` function which will be used by `schema/apply`
Refactoring and simplification:
* [`atlasaction/action.go`](diffhunk://#diff-27a1debcaa5772fc7928822261793bc1bd5ebeca936105e889fbc6a9efc93ac5L386-R407): Refactored the `MigrateDown` function to remove inline retry logic and replace it with a call to the new `waitingForApproval` function. This change simplifies the `MigrateDown` function and makes the code more modular.
* [`atlasaction/action.go`](diffhunk://#diff-27a1debcaa5772fc7928822261793bc1bd5ebe …
=> atlasaction: add a common function to handler approval flow

.github/workflows/ci-go.yaml, atlasaction/testdata/schema-apply/multiple-envs/atlas.hcl
This pull request includes several updates to the CI workflow configuration and a minor change to a test data file. The most important changes involve adding error handling and verification steps to the CI workflow.
=> .github/workflows: checking error when running test about schema/apply

atlasaction/action.go
This pull request introduces error handling improvements and refactors the timeout handling logic in the `atlasaction/action.go` file. The most important changes include adding a new error type for timeout exceeded, modifying functions to use this new error type, and updating the warning message logic.
=> atlasaction: handle timeout in approval process with specific error

.github/workflows/cd.yaml, .github/workflows/ci-go.yaml
- **.github/workflows: fixed `if` condition check when run build**
- **.github/workflows: we already run test on cd.yaml**
=> .github/workflows: fixed `if` condition check when run build

atlasaction/action.go
getting this error:
```
migrate diff with git version 2.49.0
Running "/usr/bin/git checkout test_use_auto_diff_action" got following error: error: Your local changes to the following files would be overwritten by checkout:
ent/migrate/migrations/atlas.sum
Please commit your changes or stash them before you switch branches.
Aborting
```
=> run `git checkout` in diff action before `migrate hash`

atlasaction/action.go
=> atlasaction: add guide for token

atlasaction/action.go, atlasaction/bitbucket.go, atlasaction/circleci.go, atlasaction/comments/migrate-lint.tmpl, atlasaction/github.go, atlasaction/gitlab.go, atlasaction/testdata/templates/migrate-lint.txtar
Also aligning vcs client naming.
=> atlasaction/comments/template: fix migrate lint comment template
