ariga/atlas-action

README.md

default permissions for GITHUB_TOKEN does not include` write on PR` permission
since month ago: https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/#:~:text=Previously%2C%20GitHub%20Actions%20gets%20a,to%20read%2Fwrite%20if%20needed. 
see default permissions on new repo:
https://user-images.githubusercontent.com/63970571/226176389-d6b0bf9b-6235-4b2a-b7ea-88c0f356945e.mov
Thus, with default permissions users get an `Resource not accessible by integration` Error
see failing: https://github.com/ronenlu/test_migration/actions/runs/4434852193/jobs/7781295191#step:3:69
but with the permissions specified in the README the workflow is green,
see working: https://github.com/ronenlu/test_migration/actions/runs/4460538212/jobs/7833748560? …

add GITHUB_TOKEN permissions to README

---

atlasaction/action.go
atlasaction/action_test.go

RefName is not always the name of the branch.
Sometimes, GitHub will create a temporary branch
with a name such as refs/pull/6/merge and use that as the branch name
The branch name of the source branch of a PR is given using HeadRef, but that's not available in a push trigger, so we will default to head_ref but if it's empty we will use ref_name

atlasaction: fixed branch name passed to Atlas Cloud

---

.github/workflows/ci-go.yaml
atlasaction/action.go
atlasaction/action_test.go
migrate/lint/action.yml

This change aligns the way the token is passed around to the rest of the actions online
The default value of the token was only working from inside the organization

migrate/lint: change github-token to an env var instead of an input parameter

---

.github/workflows/cd.yaml

The build was failing because the SDK now verifies that Atlas is installed

build: fix build after SDK upgrade

---

atlasaction/comment.tmpl

atlasaction: fixed comment icons size on mobile

---

.github/workflows/cd.yaml

see run: https://github.com/ariga/atlas-action/actions/runs/8004598599/job/21862364687

.github/workflow: add end to end tests

---

atlasaction/action.go
atlasaction/action_test.go
go.mod
go.sum

atlasaction: enrich run ctx with actor name and id

---

atlasaction/action.go
atlasaction/action_test.go

currently we dont send anything in the url field of the atlas context,
since we use head_commit_url field which is always empty:

fix not sending url in conext

---

.github/workflows/ci-go.yaml
README.md
atlasaction/action.go
atlasaction/action_test.go
atlasaction/mock-atlas-down.sh
atlasaction/testdata/down/1.sql
atlasaction/testdata/down/2.sql
atlasaction/testdata/down/3.sql
atlasaction/testdata/down/atlas.sum
cmd/atlas-action/main.go
go.mod
go.sum
migrate/down/action.yml
migrate/down/dist/index.js
migrate/down/index.js
migrate/lint/action.yml
migrate/push/action.yml
package.json

Have a look here: https://github.com/ariga/atlas-action/actions/runs/8423912059/job/23066659095?pr=141#step:8:26

all: add support for migrate down

---

.github/workflows/ci-go.yaml

fix failing unit tests [job](https://github.com/ariga/atlas-action/actions/runs/8433685168/job/23095256129#step:4:60):

.github: update go version in unit-tests action

---

atlasaction/action.go
atlasaction/action_test.go
atlasaction/comment.tmpl

looks like this:
<table>
<thead>
<tr>
<th>Status</th>
<th>Step</th>
<th>Link</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
1 new migration file detected
</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
ERD and visual diff generated
</td>
<td>
<a href="https://migration-lint-report-url#erd" target="_blank">View Visualization</a>
</td>
</tr>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
checksum mismatch
</td>
<td>
<a href="https://migration-lint-report-url" target="_blank">View Report</a>
</td>
</tr>
</tbody>
</table>

fix not showing error indaction for checksum mismatch atlas payload

---

atlasaction/action.go
atlasaction/action_test.go
atlasaction/comments/lint.tmpl

`atlas migrate lint` on <strong>testdata/migrations</strong>
<table>
<thead>
<tr>
<th>Status</th>
<th>Step</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
0 new migration files detected
</td>
<td>&nbsp;</td>
</tr>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
ERD and visual diff generated
</td>
<td>
<a href="https://migration-lint-report-url#erd" target="_blank">View Visualization</a>
</td>
</tr>
<tr>
<td>
<div align="center">
</div>
</td>
<td>
Detected 1 non-additive change
</td>
<td>
File 20240613102407.sql is missing or has been removed. Changes that have already been applied will not be reverted <br/>
</td>
</tr>
<td colspan="4">
<div align="center">
Read the full linting report on <a href="https://migration-lint-report-url" …

add non linear history to lint summary report

---

atlasaction/action.go
atlasaction/action_test.go
atlasaction/comments/lint.tmpl

rendered  <img width="20px" height="21px" src="https://release.ariga.io/images/assets/warning.svg"/>
instead of  <img width="20px" height="21px" src="https://release.ariga.io/images/assets/error.svg"/>
I ignored errors on the `Payload.Steps[0].Result.Error` when rendering the Icon, just checked for`Payload.Steps[0].Error`

fix template not sowing correct icon on error

---

atlasaction/action_test.go
atlasaction/comments/lint.tmpl

atlasaction/comments: use br tag instead of ul list to present files

---

.github/workflows/cd.yaml
atlasaction/action.go
atlasaction/action_test.go
cmd/atlas-action/main.go

Changes:
- Added Commit ID info into atlas-actions' version
- Build when tags pushed.
- By default, use tag or branch name for the binary (No more default to `v1`). It mean, push to the master branch will upload `atlas-action-master` instead of `atlas-action-v1`. In the following PR, I'll update the logic of shim to download the `-master` version for `@master` tag.

.github: build binary on tag, branch pushes

---

atlasaction/action.go
atlasaction/action_test.go
go.mod
go.sum
schema/push/action.yml

Wait for https://github.com/ariga/atlas-go-sdk/pull/95/files

schema/push: fix URL and support Link, Slug output

---

atlasaction/action.go
go.mod
go.sum

Fix bug caused by https://github.com/ariga/atlas-action/pull/238, I was miss understand the schema's name and `Repo` with `atlas://` as its prefix.

schema/push: fixed repo name input

---

atlasaction/action_test.go
atlasaction/circleci_action.go
atlasaction/circleci_action_test.go
atlasaction/testdata/circleci/migrate-lint.txtar

Any action that supports output will add `ATLAS_OUTPUT_<ACTION_NAME>_<OUTPUT_NAME>` to `$BASH_ENV` file.
for example the `migrate/lint` action has `report-url` output that will add `ATLAS_OUTPUT_MIGRATE_LINT_REPORT_URL`. `/`, `-`, and ` ` (space) will be replaced with `_`, and all characters will be in upper case.
More detail: https://circleci.com/docs/env-vars/#parameters-and-bash-environment
> Another possible method to interpolate values into your configuration is to use a run step to export environment variables to BASH_ENV, as shown below.
> In every step, CircleCI uses bash to source BASH_ENV. This means that BASH_ENV is automatically loaded and run, allowing you to use interpolation and share environment variables across run steps.

atlasaction: support output for circle-ci

---

.github/workflows/ci-go.yaml
atlasaction/action.go
atlasaction/action_test.go

this PR moves the login logic from atlas step to monitor step, thus we dont pass the `cloud-token` twice in the yaml

dont pass cloud-token twice in schema monitor action

---

atlasaction/action.go
atlasaction/bitbucket.go
atlasaction/bitbucket_test.go
atlasaction/gh_action.go
atlasaction/testdata/bitbucket/schema-push.txtar
go.mod
go.sum

- **chore: cleanup action options**
- **atlasaction: initial bitbucket pipe**

atlasaction: initial bitbucket pipe

---

atlasaction/gitlab_ci.go
atlasaction/gitlab_ci_test.go

This fixed the issue when the user use the `working-directory` input to change the CWD of action to sub-directory.

gitlab: write the `.env` to `$CI_PROJECT_DIR/.env` instead of CWD

---

README.md
migrate/apply/action.yml
schema/apply/action.yml

This pull request includes changes to add a new `tx-mode` input parameter for specifying the transaction mode for migrations. The changes are made across multiple files to ensure consistency and proper documentation.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R263): Added the `tx-mode` parameter description under the sections for inputs in the migration configuration. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R263) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R368)
* [`migrate/apply/action.yml`](diffhunk://#diff-f0659287a2a21eb4b307db47bfa1e9f3f93cbdbb1dcd4c57087940843d14d861R44-R47): Introduced the `tx-mode` parameter with a description and default …

chore: add `tx-mode` input for migration/schema apply

---

.github/workflows/ci-go.yaml
atlasaction/action.go
atlasaction/action_test.go

Now user can `git pull origin` the changes created by the action without facing conflicts:
example [run](https://github.com/ariga/atlas-action/pull/352)

atlasaction: use `merge` instead of `rebase` in migrate/autorebase

---

atlasaction/action.go
atlasaction/action_test.go
atlasaction/circleci_action_test.go
atlasaction/testdata/circleci/migrate-auto-rebase.txtar

- **atlasaction: ensure files are in the right order**
- **atlasaction: refactor logic exec and change default message**

atlasaction: refactor logic exec and change default merge message

---

atlasaction/action.go

This PR avoids a potential bug when running the approval process where two plans have the same name. Besides that, it also refactors minor things

atlasaction: use plan URL instead name when checking plan for approval
